# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: spencer.wtf
tagline: "I build tech products to solve hard problems"
email: spencerlloyddixon@gmail.com
description: Spencer Dixon is a Senior Ruby and Python Developer with 11+ years of experience building software for UK Government Digital Services and global conservation efforts. Technical articles on ruby, python and software architecture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spencer.wtf" # the base hostname & protocol for your site
twitter_username: spencerldixon
github_username: spencerldixon
author:
  name: Spencer Dixon
  twitter: spencerldixon
  url: https://spencer.wtf
logo: /assets/images/headshot.jpg
og_image: /assets/images/ogimage.png
social:
  name: Spencer Dixon
  links:
    - https://twitter.com/spencerldixon
    - https://github.com/spencerldixon
    - https://linkedin.com/in/spencerldixon
    - https://bsky.app/profile/spencerldixon.bsky.social

# Build settings
# theme: 
plugins:
  - jekyll-feed
  - jekyll-postcss-v2
  - jekyll-paginate
  - jemoji
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts: 
    disable: true
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
